CREATE DATABASE IF NOT EXISTS OSM2DB DEFAULT CHARACTER SET=UTF8;

GRANT ALL PRIVILEGES ON OSM2DB.* TO 'osm_app'@localhost IDENTIFIED BY 'v9SjBJVm';
FLUSH PRIVILEGES;

GRANT ALL PRIVILEGES ON OSM2DB.* TO 'osm_app'@'%' IDENTIFIED BY 'v9SjBJVm';
FLUSH PRIVILEGES;

Use OSM2DB;